// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizador/Lexer.jflex

package analizador;

import java_cup.runtime.*;
import reportes.ErrorLexicoSintactico;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO_MULTILINEA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\4\0\1\7\1\0\1\10\1\11\1\12\1\0"+
    "\1\13\1\0\1\14\1\15\12\16\1\17\1\0\1\20"+
    "\1\21\1\22\2\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\2\34\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\34\1\50\1\34\1\51\1\0\1\52\1\0"+
    "\1\53\1\0\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\2\34\1\65\1\66\1\67\1\70"+
    "\1\71\1\34\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\1\34\1\100\1\34\1\101\1\102\1\103\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\1\1\12\10\13\1\14"+
    "\1\15\20\13\1\16\1\1\1\17\1\2\1\20\1\21"+
    "\1\22\1\23\1\0\1\24\1\25\1\26\17\13\1\27"+
    "\22\13\1\30\1\31\1\32\33\13\1\33\20\13\1\34"+
    "\5\13\1\35\7\13\1\36\1\37\7\13\1\40\2\13"+
    "\1\41\1\13\1\42\2\13\1\43\7\13\1\44\4\13"+
    "\1\45\7\13\1\46\4\13\1\47\32\13\1\50\1\13"+
    "\1\51\17\13\1\52\1\53\5\13\1\54\4\13\1\55"+
    "\1\13\1\56\7\13\1\57\1\13\1\60\3\13\1\61"+
    "\4\13\1\62\30\13\1\63\27\13\1\64\7\13\1\65"+
    "\4\13\1\66\20\13\1\67\6\13\1\70\1\71\1\13"+
    "\1\72\1\73\12\13\1\74\1\75\2\13\1\76\2\13"+
    "\1\77\3\13\1\100\6\13\1\101\1\13\1\102\1\103"+
    "\10\13\1\104\4\13\1\105\2\13\1\106\5\13\1\107"+
    "\2\13\1\110\5\13\1\111\1\112\3\13\1\113\1\114"+
    "\4\13\1\115\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[437];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\210\0\314\0\u0110\0\u0154\0\210"+
    "\0\210\0\210\0\u0198\0\u01dc\0\210\0\u0220\0\u0264\0\u02a8"+
    "\0\u02ec\0\u0330\0\u0374\0\u03b8\0\u03fc\0\u0440\0\u0484\0\u04c8"+
    "\0\210\0\210\0\u050c\0\u0550\0\u0594\0\u05d8\0\u061c\0\u0660"+
    "\0\u06a4\0\u06e8\0\u072c\0\u0770\0\u07b4\0\u07f8\0\u083c\0\u0880"+
    "\0\u08c4\0\u0908\0\210\0\u094c\0\210\0\u0990\0\210\0\210"+
    "\0\210\0\u09d4\0\u0a18\0\210\0\210\0\210\0\u0a5c\0\u0aa0"+
    "\0\u0ae4\0\u0b28\0\u0b6c\0\u0bb0\0\u0bf4\0\u0c38\0\u0c7c\0\u0cc0"+
    "\0\u0d04\0\u0d48\0\u0d8c\0\u0dd0\0\u0e14\0\u0330\0\u0e58\0\u0e9c"+
    "\0\u0ee0\0\u0f24\0\u0f68\0\u0fac\0\u0ff0\0\u1034\0\u1078\0\u10bc"+
    "\0\u1100\0\u1144\0\u1188\0\u11cc\0\u1210\0\u1254\0\u1298\0\u12dc"+
    "\0\210\0\210\0\u0a18\0\u1320\0\u1364\0\u13a8\0\u13ec\0\u1430"+
    "\0\u1474\0\u14b8\0\u14fc\0\u1540\0\u1584\0\u15c8\0\u160c\0\u1650"+
    "\0\u1694\0\u16d8\0\u171c\0\u1760\0\u17a4\0\u17e8\0\u182c\0\u1870"+
    "\0\u18b4\0\u18f8\0\u193c\0\u1980\0\u19c4\0\u1a08\0\u0330\0\u1a4c"+
    "\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c\0\u1ba0\0\u1be4\0\u1c28\0\u1c6c"+
    "\0\u1cb0\0\u1cf4\0\u1d38\0\u1d7c\0\u1dc0\0\u1e04\0\u1e48\0\u0330"+
    "\0\u1e8c\0\u1ed0\0\u1f14\0\u1f58\0\u1f9c\0\u0330\0\u1fe0\0\u2024"+
    "\0\u2068\0\u20ac\0\u20f0\0\u2134\0\u2178\0\u21bc\0\u0330\0\u2200"+
    "\0\u2244\0\u2288\0\u22cc\0\u2310\0\u2354\0\u2398\0\u0330\0\u23dc"+
    "\0\u2420\0\u0330\0\u2464\0\u0330\0\u24a8\0\u24ec\0\u0330\0\u2530"+
    "\0\u2574\0\u25b8\0\u25fc\0\u2640\0\u2684\0\u26c8\0\u0330\0\u270c"+
    "\0\u2750\0\u2794\0\u27d8\0\u0330\0\u281c\0\u2860\0\u28a4\0\u28e8"+
    "\0\u292c\0\u2970\0\u29b4\0\u0330\0\u29f8\0\u2a3c\0\u2a80\0\u2ac4"+
    "\0\u0330\0\u2b08\0\u2b4c\0\u2b90\0\u2bd4\0\u2c18\0\u2c5c\0\u2ca0"+
    "\0\u2ce4\0\u2d28\0\u2d6c\0\u2db0\0\u2df4\0\u2e38\0\u2e7c\0\u2ec0"+
    "\0\u2f04\0\u2f48\0\u2f8c\0\u2fd0\0\u3014\0\u3058\0\u309c\0\u30e0"+
    "\0\u3124\0\u3168\0\u31ac\0\u0330\0\u31f0\0\u0330\0\u3234\0\u3278"+
    "\0\u32bc\0\u3300\0\u3344\0\u3388\0\u33cc\0\u3410\0\u3454\0\u3498"+
    "\0\u34dc\0\u3520\0\u3564\0\u35a8\0\u35ec\0\u0330\0\u0330\0\u3630"+
    "\0\u3674\0\u36b8\0\u36fc\0\u3740\0\u0330\0\u3784\0\u37c8\0\u380c"+
    "\0\u3850\0\u0330\0\u3894\0\u0330\0\u38d8\0\u391c\0\u3960\0\u39a4"+
    "\0\u39e8\0\u3a2c\0\u3a70\0\u3ab4\0\u3af8\0\u0330\0\u3b3c\0\u3b80"+
    "\0\u3bc4\0\u0330\0\u3c08\0\u3c4c\0\u3c90\0\u3cd4\0\u3d18\0\u3d5c"+
    "\0\u3da0\0\u3de4\0\u3e28\0\u3e6c\0\u3eb0\0\u3ef4\0\u3f38\0\u3f7c"+
    "\0\u3fc0\0\u4004\0\u4048\0\u408c\0\u40d0\0\u4114\0\u4158\0\u419c"+
    "\0\u41e0\0\u4224\0\u4268\0\u42ac\0\u42f0\0\u4334\0\u4378\0\u0330"+
    "\0\u43bc\0\u4400\0\u4444\0\u4488\0\u44cc\0\u4510\0\u4554\0\u4598"+
    "\0\u45dc\0\u4620\0\u4664\0\u46a8\0\u46ec\0\u4730\0\u4774\0\u47b8"+
    "\0\u47fc\0\u4840\0\u4884\0\u48c8\0\u490c\0\u4950\0\u4994\0\u49d8"+
    "\0\u4a1c\0\u4a60\0\u4aa4\0\u4ae8\0\u4b2c\0\u4b70\0\u4bb4\0\u0330"+
    "\0\u4bf8\0\u4c3c\0\u4c80\0\u4cc4\0\u0330\0\u4d08\0\u4d4c\0\u4d90"+
    "\0\u4dd4\0\u4e18\0\u4e5c\0\u4ea0\0\u4ee4\0\u4f28\0\u4f6c\0\u4fb0"+
    "\0\u4ff4\0\u5038\0\u507c\0\u50c0\0\u5104\0\u0330\0\u5148\0\u518c"+
    "\0\u51d0\0\u5214\0\u5258\0\u529c\0\u0330\0\u0330\0\u52e0\0\u0330"+
    "\0\u0330\0\u5324\0\u5368\0\u53ac\0\u53f0\0\u5434\0\u5478\0\u54bc"+
    "\0\u5500\0\u5544\0\u5588\0\u0330\0\u0330\0\u55cc\0\u5610\0\u0330"+
    "\0\u5654\0\u5698\0\u0330\0\u56dc\0\u5720\0\u5764\0\u0330\0\u57a8"+
    "\0\u57ec\0\u5830\0\u5874\0\u58b8\0\u58fc\0\u0330\0\u5940\0\u0330"+
    "\0\u5984\0\u59c8\0\u5a0c\0\u5a50\0\u5a94\0\u5ad8\0\u5b1c\0\u5b60"+
    "\0\u5ba4\0\u0330\0\u5be8\0\u5c2c\0\u5c70\0\u5cb4\0\u0330\0\u5cf8"+
    "\0\u5d3c\0\u0330\0\u5d80\0\u5dc4\0\u5e08\0\u5e4c\0\u5e90\0\u0330"+
    "\0\u5ed4\0\u5f18\0\u0330\0\u5f5c\0\u5fa0\0\u5fe4\0\u6028\0\u606c"+
    "\0\u0330\0\u0330\0\u60b0\0\u60f4\0\u6138\0\u0330\0\u0330\0\u617c"+
    "\0\u61c0\0\u6204\0\u6248\0\u0330\0\u0330";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[437];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\3\1\12\1\3\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\4\22\1\23\1\22\1\24\4\22"+
    "\1\25\2\22\1\26\1\27\3\22\1\30\1\22\1\31"+
    "\1\32\2\22\1\33\1\22\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\22\1\44\1\45\1\46"+
    "\1\47\1\50\1\22\1\51\1\52\1\22\1\53\1\54"+
    "\1\55\12\4\1\56\71\4\106\0\1\4\122\0\1\57"+
    "\71\0\1\60\106\0\1\61\2\0\1\62\102\0\1\63"+
    "\1\0\1\14\106\0\1\64\103\0\1\65\103\0\1\66"+
    "\100\0\1\22\4\0\17\22\1\67\6\22\2\0\26\22"+
    "\21\0\1\22\4\0\26\22\2\0\26\22\21\0\1\22"+
    "\4\0\10\22\1\70\15\22\2\0\26\22\21\0\1\22"+
    "\4\0\4\22\1\71\21\22\2\0\26\22\21\0\1\22"+
    "\4\0\1\72\3\22\1\73\21\22\2\0\26\22\21\0"+
    "\1\22\4\0\4\22\1\74\21\22\2\0\26\22\21\0"+
    "\1\22\4\0\7\22\1\75\3\22\1\76\12\22\2\0"+
    "\26\22\21\0\1\22\4\0\1\77\25\22\2\0\26\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\100\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\22\1\101\24\22"+
    "\21\0\1\22\4\0\26\22\2\0\12\22\1\102\13\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\22\1\103\24\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\104\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\105\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\6\22\1\106\5\22"+
    "\1\107\11\22\21\0\1\22\4\0\26\22\2\0\1\22"+
    "\1\110\13\22\1\111\10\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\112\24\22\21\0\1\22\4\0\26\22"+
    "\2\0\16\22\1\113\7\22\21\0\1\22\4\0\26\22"+
    "\2\0\12\22\1\114\13\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\22\1\115\13\22\1\116\4\22\1\117\3\22"+
    "\21\0\1\22\4\0\26\22\2\0\3\22\1\120\1\22"+
    "\1\121\14\22\1\122\3\22\21\0\1\22\4\0\26\22"+
    "\2\0\10\22\1\123\4\22\1\124\1\22\1\125\6\22"+
    "\21\0\1\22\4\0\26\22\2\0\11\22\1\126\14\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\22\1\127\7\22"+
    "\1\130\14\22\105\0\1\131\16\0\1\132\66\0\2\62"+
    "\4\0\76\62\16\0\1\133\103\0\1\22\4\0\2\22"+
    "\1\134\23\22\2\0\26\22\21\0\1\22\4\0\17\22"+
    "\1\135\6\22\2\0\26\22\21\0\1\22\4\0\1\136"+
    "\25\22\2\0\26\22\21\0\1\22\4\0\6\22\1\137"+
    "\17\22\2\0\26\22\21\0\1\22\4\0\3\22\1\140"+
    "\22\22\2\0\26\22\21\0\1\22\4\0\20\22\1\141"+
    "\5\22\2\0\26\22\21\0\1\22\4\0\10\22\1\142"+
    "\15\22\2\0\26\22\21\0\1\22\4\0\1\143\25\22"+
    "\2\0\26\22\21\0\1\22\4\0\17\22\1\144\6\22"+
    "\2\0\26\22\21\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\145\11\22\21\0\1\22\4\0\26\22\2\0\13\22"+
    "\1\146\12\22\21\0\1\22\4\0\26\22\2\0\20\22"+
    "\1\147\5\22\21\0\1\22\4\0\26\22\2\0\11\22"+
    "\1\150\1\151\13\22\21\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\152\4\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\22\1\153\24\22\21\0\1\22\4\0\26\22\2\0"+
    "\11\22\1\154\14\22\21\0\1\22\4\0\26\22\2\0"+
    "\20\22\1\155\5\22\21\0\1\22\4\0\26\22\2\0"+
    "\24\22\1\156\1\22\21\0\1\22\4\0\26\22\2\0"+
    "\7\22\1\157\1\22\1\160\7\22\1\161\4\22\21\0"+
    "\1\22\4\0\26\22\2\0\16\22\1\162\7\22\21\0"+
    "\1\22\4\0\26\22\2\0\1\22\1\163\24\22\21\0"+
    "\1\22\4\0\26\22\2\0\14\22\1\164\11\22\21\0"+
    "\1\22\4\0\26\22\2\0\22\22\1\165\3\22\21\0"+
    "\1\22\4\0\26\22\2\0\12\22\1\166\1\22\1\167"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\15\22\1\170"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\5\22\1\171"+
    "\4\22\1\172\13\22\21\0\1\22\4\0\26\22\2\0"+
    "\3\22\1\173\22\22\21\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\174\20\22\21\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\175\4\22\21\0\1\22\4\0\26\22\2\0"+
    "\22\22\1\176\3\22\21\0\1\22\4\0\26\22\2\0"+
    "\3\22\1\177\22\22\21\0\1\22\4\0\26\22\2\0"+
    "\17\22\1\200\6\22\21\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\201\4\22\21\0\1\22\4\0\1\202\25\22"+
    "\2\0\26\22\21\0\1\22\4\0\4\22\1\203\21\22"+
    "\2\0\26\22\21\0\1\22\4\0\13\22\1\204\7\22"+
    "\1\205\2\22\2\0\26\22\21\0\1\22\4\0\10\22"+
    "\1\206\15\22\2\0\26\22\21\0\1\22\4\0\10\22"+
    "\1\207\15\22\2\0\26\22\21\0\1\22\4\0\21\22"+
    "\1\210\4\22\2\0\26\22\21\0\1\22\4\0\4\22"+
    "\1\211\21\22\2\0\26\22\21\0\1\22\4\0\20\22"+
    "\1\212\5\22\2\0\26\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\213\25\22\21\0\1\22\4\0\26\22\2\0"+
    "\22\22\1\214\3\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\22\1\215\24\22\21\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\216\20\22\21\0\1\22\4\0\26\22\2\0"+
    "\12\22\1\217\13\22\21\0\1\22\4\0\26\22\2\0"+
    "\20\22\1\220\5\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\221\25\22\21\0\1\22\4\0\26\22\2\0\12\22"+
    "\1\222\13\22\21\0\1\22\4\0\26\22\2\0\21\22"+
    "\1\223\4\22\21\0\1\22\4\0\26\22\2\0\21\22"+
    "\1\224\4\22\21\0\1\22\4\0\26\22\2\0\1\225"+
    "\25\22\21\0\1\22\4\0\26\22\2\0\5\22\1\226"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\14\22\1\227"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\3\22\1\230"+
    "\22\22\21\0\1\22\4\0\26\22\2\0\15\22\1\231"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\25\22\1\232"+
    "\21\0\1\22\4\0\26\22\2\0\4\22\1\233\21\22"+
    "\21\0\1\22\4\0\26\22\2\0\14\22\1\234\11\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\235\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\17\22\1\236\6\22"+
    "\21\0\1\22\4\0\26\22\2\0\4\22\1\237\21\22"+
    "\21\0\1\22\4\0\26\22\2\0\6\22\1\240\17\22"+
    "\21\0\1\22\4\0\26\22\2\0\3\22\1\241\22\22"+
    "\21\0\1\22\4\0\26\22\2\0\14\22\1\242\11\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\22\1\243\24\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\244\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\21\22\1\245\4\22"+
    "\21\0\1\22\4\0\26\22\2\0\17\22\1\246\6\22"+
    "\21\0\1\22\4\0\26\22\2\0\10\22\1\247\15\22"+
    "\21\0\1\22\4\0\15\22\1\250\10\22\2\0\26\22"+
    "\21\0\1\22\4\0\1\22\1\251\24\22\2\0\26\22"+
    "\21\0\1\22\4\0\10\22\1\252\15\22\2\0\26\22"+
    "\21\0\1\22\4\0\25\22\1\253\2\0\26\22\21\0"+
    "\1\22\4\0\2\22\1\254\23\22\2\0\26\22\21\0"+
    "\1\22\4\0\21\22\1\255\4\22\2\0\26\22\21\0"+
    "\1\22\4\0\13\22\1\256\12\22\2\0\26\22\21\0"+
    "\1\22\4\0\7\22\1\257\16\22\2\0\26\22\21\0"+
    "\1\22\4\0\2\22\1\260\23\22\2\0\26\22\21\0"+
    "\1\22\4\0\26\22\2\0\20\22\1\261\5\22\21\0"+
    "\1\22\4\0\26\22\2\0\7\22\1\262\16\22\21\0"+
    "\1\22\4\0\26\22\2\0\5\22\1\263\20\22\21\0"+
    "\1\22\4\0\26\22\2\0\5\22\1\264\20\22\21\0"+
    "\1\22\4\0\26\22\2\0\12\22\1\265\1\266\12\22"+
    "\21\0\1\22\4\0\26\22\2\0\11\22\1\267\14\22"+
    "\21\0\1\22\4\0\26\22\2\0\11\22\1\270\14\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\271\25\22\21\0"+
    "\1\22\4\0\26\22\2\0\10\22\1\272\15\22\21\0"+
    "\1\22\4\0\26\22\2\0\1\273\25\22\21\0\1\22"+
    "\4\0\26\22\2\0\10\22\1\274\15\22\21\0\1\22"+
    "\4\0\26\22\2\0\14\22\1\275\11\22\21\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\276\20\22\21\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\277\10\22\21\0\1\22"+
    "\4\0\26\22\2\0\4\22\1\300\21\22\21\0\1\22"+
    "\4\0\26\22\2\0\20\22\1\301\5\22\21\0\1\22"+
    "\4\0\26\22\2\0\11\22\1\302\14\22\21\0\1\22"+
    "\4\0\26\22\2\0\1\303\25\22\21\0\1\22\4\0"+
    "\26\22\2\0\5\22\1\304\20\22\21\0\1\22\4\0"+
    "\26\22\2\0\12\22\1\305\13\22\21\0\1\22\4\0"+
    "\26\22\2\0\15\22\1\306\10\22\21\0\1\22\4\0"+
    "\26\22\2\0\11\22\1\307\14\22\21\0\1\22\4\0"+
    "\4\22\1\310\21\22\2\0\26\22\21\0\1\22\4\0"+
    "\1\311\25\22\2\0\26\22\21\0\1\22\4\0\15\22"+
    "\1\312\10\22\2\0\26\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\313\25\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\314\25\22\21\0\1\22\4\0\1\315\25\22\2\0"+
    "\26\22\21\0\1\22\4\0\3\22\1\316\22\22\2\0"+
    "\26\22\21\0\1\22\4\0\17\22\1\317\6\22\2\0"+
    "\26\22\21\0\1\22\4\0\26\22\2\0\5\22\1\320"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\5\22\1\321"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\4\22\1\322"+
    "\21\22\21\0\1\22\4\0\26\22\2\0\1\22\1\323"+
    "\24\22\21\0\1\22\4\0\26\22\2\0\15\22\1\324"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\14\22\1\325"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\1\22\1\326"+
    "\24\22\21\0\1\22\4\0\26\22\2\0\13\22\1\327"+
    "\12\22\21\0\1\22\4\0\26\22\2\0\5\22\1\330"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\3\22\1\331"+
    "\22\22\21\0\1\22\4\0\26\22\2\0\5\22\1\332"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\17\22\1\333"+
    "\6\22\21\0\1\22\4\0\26\22\2\0\13\22\1\334"+
    "\12\22\21\0\1\22\4\0\26\22\2\0\1\335\17\22"+
    "\1\336\5\22\21\0\1\22\4\0\26\22\2\0\14\22"+
    "\1\337\11\22\21\0\1\22\4\0\26\22\2\0\10\22"+
    "\1\340\6\22\1\341\1\342\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\343\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\1\344\25\22\21\0\1\22\4\0\26\22"+
    "\2\0\17\22\1\345\6\22\21\0\1\22\4\0\26\22"+
    "\2\0\15\22\1\346\10\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\347\25\22\21\0\1\22\4\0\13\22\1\350"+
    "\12\22\2\0\26\22\21\0\1\22\4\0\6\22\1\351"+
    "\17\22\2\0\26\22\21\0\1\22\4\0\20\22\1\352"+
    "\5\22\2\0\26\22\21\0\1\22\4\0\1\22\1\353"+
    "\24\22\2\0\26\22\21\0\1\22\4\0\21\22\1\354"+
    "\4\22\2\0\26\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\355\25\22\21\0\1\22\4\0\25\22\1\356\2\0"+
    "\26\22\21\0\1\22\4\0\26\22\2\0\20\22\1\357"+
    "\5\22\21\0\1\22\4\0\26\22\2\0\1\360\25\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\361\25\22\21\0"+
    "\1\22\4\0\26\22\2\0\20\22\1\362\5\22\21\0"+
    "\1\22\4\0\26\22\2\0\23\22\1\363\2\22\21\0"+
    "\1\22\4\0\26\22\2\0\7\22\1\364\16\22\21\0"+
    "\1\22\4\0\26\22\2\0\12\22\1\365\13\22\21\0"+
    "\1\22\4\0\26\22\2\0\15\22\1\366\10\22\21\0"+
    "\1\22\4\0\26\22\2\0\1\22\1\367\24\22\21\0"+
    "\1\22\4\0\26\22\2\0\15\22\1\370\10\22\21\0"+
    "\1\22\4\0\26\22\2\0\14\22\1\371\11\22\21\0"+
    "\1\22\4\0\26\22\2\0\20\22\1\372\5\22\21\0"+
    "\1\22\4\0\26\22\2\0\14\22\1\373\11\22\21\0"+
    "\1\22\4\0\26\22\2\0\7\22\1\374\16\22\21\0"+
    "\1\22\4\0\26\22\2\0\5\22\1\375\3\22\1\376"+
    "\14\22\21\0\1\22\4\0\26\22\2\0\5\22\1\377"+
    "\20\22\21\0\1\22\4\0\26\22\2\0\3\22\1\u0100"+
    "\22\22\21\0\1\22\4\0\26\22\2\0\20\22\1\u0101"+
    "\5\22\21\0\1\22\4\0\26\22\2\0\17\22\1\u0102"+
    "\6\22\21\0\1\22\4\0\26\22\2\0\25\22\1\u0103"+
    "\21\0\1\22\4\0\26\22\2\0\17\22\1\u0104\6\22"+
    "\21\0\1\22\4\0\1\22\1\u0105\24\22\2\0\26\22"+
    "\21\0\1\22\4\0\13\22\1\u0106\12\22\2\0\26\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\u0107\25\22\21\0"+
    "\1\22\4\0\21\22\1\u0108\4\22\2\0\26\22\21\0"+
    "\1\22\4\0\1\u0109\25\22\2\0\26\22\21\0\1\22"+
    "\4\0\4\22\1\u010a\21\22\2\0\26\22\21\0\1\22"+
    "\4\0\1\22\1\u010b\24\22\2\0\26\22\21\0\1\22"+
    "\4\0\26\22\2\0\16\22\1\u010c\7\22\21\0\1\22"+
    "\4\0\26\22\2\0\1\22\1\u010d\24\22\21\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\u010e\4\22\21\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\u010f\20\22\21\0\1\22"+
    "\4\0\26\22\2\0\1\u0110\25\22\21\0\1\22\4\0"+
    "\26\22\2\0\23\22\1\u0111\2\22\21\0\1\22\4\0"+
    "\26\22\2\0\12\22\1\u0112\13\22\21\0\1\22\4\0"+
    "\26\22\2\0\13\22\1\u0113\12\22\21\0\1\22\4\0"+
    "\26\22\2\0\21\22\1\u0114\4\22\21\0\1\22\4\0"+
    "\26\22\2\0\22\22\1\u0115\3\22\21\0\1\22\4\0"+
    "\26\22\2\0\1\22\1\u0116\24\22\21\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\u0117\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\u0118\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\15\22\1\u0119\10\22\21\0\1\22\4\0"+
    "\26\22\2\0\6\22\1\u011a\17\22\21\0\1\22\4\0"+
    "\26\22\2\0\15\22\1\u011b\10\22\21\0\1\22\4\0"+
    "\26\22\2\0\1\u011c\25\22\21\0\1\22\4\0\26\22"+
    "\2\0\1\u011d\25\22\21\0\1\22\4\0\16\22\1\u011e"+
    "\7\22\2\0\26\22\21\0\1\22\4\0\17\22\1\u011f"+
    "\6\22\2\0\26\22\21\0\1\22\4\0\17\22\1\u0120"+
    "\6\22\2\0\26\22\21\0\1\22\4\0\17\22\1\u0121"+
    "\6\22\2\0\26\22\21\0\1\22\4\0\13\22\1\u0122"+
    "\12\22\2\0\26\22\21\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u0123\10\22\21\0\1\22\4\0\26\22\2\0"+
    "\3\22\1\u0124\22\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\u0125\25\22\21\0\1\22\4\0\26\22\2\0\20\22"+
    "\1\u0126\5\22\21\0\1\22\4\0\26\22\2\0\16\22"+
    "\1\u0127\7\22\21\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\u0128\20\22\21\0\1\22\4\0\26\22\2\0\21\22"+
    "\1\u0129\4\22\21\0\1\22\4\0\26\22\2\0\2\22"+
    "\1\u012a\23\22\21\0\1\22\4\0\26\22\2\0\1\u012b"+
    "\25\22\21\0\1\22\4\0\26\22\2\0\13\22\1\u012c"+
    "\12\22\21\0\1\22\4\0\26\22\2\0\12\22\1\u012d"+
    "\13\22\21\0\1\22\4\0\26\22\2\0\21\22\1\u012e"+
    "\4\22\21\0\1\22\4\0\26\22\2\0\15\22\1\u012f"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\17\22\1\u0130"+
    "\6\22\21\0\1\22\4\0\26\22\2\0\22\22\1\u0131"+
    "\3\22\21\0\1\22\4\0\26\22\2\0\22\22\1\u0132"+
    "\3\22\21\0\1\22\4\0\26\22\2\0\2\22\1\u0133"+
    "\23\22\21\0\1\22\4\0\26\22\2\0\3\22\1\u0134"+
    "\22\22\21\0\1\22\4\0\13\22\1\u0135\12\22\2\0"+
    "\26\22\21\0\1\22\4\0\22\22\1\u0136\3\22\2\0"+
    "\26\22\21\0\1\22\4\0\10\22\1\u0137\15\22\2\0"+
    "\26\22\21\0\1\22\4\0\17\22\1\u0138\6\22\2\0"+
    "\26\22\21\0\1\22\4\0\16\22\1\u0139\7\22\2\0"+
    "\26\22\21\0\1\22\4\0\26\22\2\0\11\22\1\u013a"+
    "\14\22\21\0\1\22\4\0\26\22\2\0\21\22\1\u013b"+
    "\4\22\21\0\1\22\4\0\26\22\2\0\14\22\1\u013c"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\1\u013d\25\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u013e\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\10\22\1\u013f\15\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u0140\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\10\22\1\u0141\6\22"+
    "\1\u0142\1\u0143\5\22\21\0\1\22\4\0\26\22\2\0"+
    "\2\22\1\u0144\23\22\21\0\1\22\4\0\26\22\2\0"+
    "\21\22\1\u0145\4\22\21\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u0146\10\22\21\0\1\22\4\0\26\22\2\0"+
    "\22\22\1\u0147\3\22\21\0\1\22\4\0\26\22\2\0"+
    "\5\22\1\u0148\20\22\21\0\1\22\4\0\26\22\2\0"+
    "\12\22\1\u0149\13\22\21\0\1\22\4\0\26\22\2\0"+
    "\14\22\1\u014a\11\22\21\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u014b\10\22\21\0\1\22\4\0\26\22\2\0"+
    "\15\22\1\u014c\10\22\21\0\1\22\4\0\21\22\1\u014d"+
    "\4\22\2\0\26\22\21\0\1\22\4\0\15\22\1\u014e"+
    "\10\22\2\0\26\22\21\0\1\22\4\0\12\22\1\u014f"+
    "\13\22\2\0\26\22\21\0\1\22\4\0\10\22\1\u0150"+
    "\15\22\2\0\26\22\21\0\1\22\4\0\2\22\1\u0151"+
    "\23\22\2\0\26\22\21\0\1\22\4\0\26\22\2\0"+
    "\14\22\1\u0152\11\22\21\0\1\22\4\0\26\22\2\0"+
    "\11\22\1\u0153\14\22\21\0\1\22\4\0\26\22\2\0"+
    "\1\u0154\25\22\21\0\1\22\4\0\26\22\2\0\3\22"+
    "\1\u0155\22\22\21\0\1\22\4\0\26\22\2\0\11\22"+
    "\1\u0156\14\22\21\0\1\22\4\0\26\22\2\0\1\u0157"+
    "\25\22\21\0\1\22\4\0\26\22\2\0\1\u0158\25\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\u0159\3\22"+
    "\1\u015a\14\22\21\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\u015b\20\22\21\0\1\22\4\0\26\22\2\0\3\22"+
    "\1\u015c\22\22\21\0\1\22\4\0\26\22\2\0\5\22"+
    "\1\u015d\20\22\21\0\1\22\4\0\26\22\2\0\10\22"+
    "\1\u015e\15\22\21\0\1\22\4\0\26\22\2\0\17\22"+
    "\1\u015f\6\22\21\0\1\22\4\0\26\22\2\0\17\22"+
    "\1\u0160\6\22\21\0\1\22\4\0\26\22\2\0\1\u0161"+
    "\25\22\21\0\1\22\4\0\26\22\2\0\4\22\1\u0162"+
    "\21\22\21\0\1\22\4\0\26\22\2\0\14\22\1\u0163"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\13\22\1\u0164"+
    "\12\22\21\0\1\22\4\0\4\22\1\u0165\21\22\2\0"+
    "\26\22\21\0\1\22\4\0\4\22\1\u0166\21\22\2\0"+
    "\26\22\21\0\1\22\4\0\4\22\1\u0167\21\22\2\0"+
    "\26\22\21\0\1\22\4\0\12\22\1\u0168\13\22\2\0"+
    "\26\22\21\0\1\22\4\0\26\22\2\0\21\22\1\u0169"+
    "\4\22\21\0\1\22\4\0\26\22\2\0\15\22\1\u016a"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\13\22\1\u016b"+
    "\12\22\21\0\1\22\4\0\26\22\2\0\15\22\1\u016c"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\14\22\1\u016d"+
    "\11\22\21\0\1\22\4\0\26\22\2\0\23\22\1\u016e"+
    "\2\22\21\0\1\22\4\0\26\22\2\0\16\22\1\u016f"+
    "\7\22\21\0\1\22\4\0\26\22\2\0\1\22\1\u0170"+
    "\24\22\21\0\1\22\4\0\26\22\2\0\20\22\1\u0171"+
    "\5\22\21\0\1\22\4\0\26\22\2\0\20\22\1\u0172"+
    "\5\22\21\0\1\22\4\0\26\22\2\0\15\22\1\u0173"+
    "\10\22\21\0\1\22\4\0\26\22\2\0\17\22\1\u0174"+
    "\6\22\21\0\1\22\4\0\26\22\2\0\25\22\1\u0175"+
    "\21\0\1\22\4\0\26\22\2\0\3\22\1\u0176\22\22"+
    "\21\0\1\22\4\0\26\22\2\0\4\22\1\u0177\21\22"+
    "\21\0\1\22\4\0\26\22\2\0\20\22\1\u0178\5\22"+
    "\21\0\1\22\4\0\26\22\2\0\22\22\1\u0179\3\22"+
    "\21\0\1\22\4\0\26\22\2\0\2\22\1\u017a\23\22"+
    "\21\0\1\22\4\0\17\22\1\u017b\6\22\2\0\26\22"+
    "\21\0\1\22\4\0\26\22\2\0\14\22\1\u017c\11\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u017d\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\22\22\1\u017e\3\22"+
    "\21\0\1\22\4\0\26\22\2\0\21\22\1\u017f\4\22"+
    "\21\0\1\22\4\0\26\22\2\0\11\22\1\u0180\14\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u0181\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\12\22\1\u0182\13\22"+
    "\21\0\1\22\4\0\26\22\2\0\21\22\1\u0183\4\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u0184\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\17\22\1\u0185\6\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\u0186\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\5\22\1\u0187\20\22"+
    "\21\0\1\22\4\0\26\22\2\0\20\22\1\u0188\5\22"+
    "\21\0\1\22\4\0\26\22\2\0\15\22\1\u0189\10\22"+
    "\21\0\1\22\4\0\26\22\2\0\1\u018a\25\22\21\0"+
    "\1\22\4\0\26\22\2\0\23\22\1\u018b\2\22\21\0"+
    "\1\22\4\0\26\22\2\0\14\22\1\u018c\11\22\21\0"+
    "\1\22\4\0\26\22\2\0\3\22\1\u018d\22\22\21\0"+
    "\1\22\4\0\26\22\2\0\11\22\1\u018e\14\22\21\0"+
    "\1\22\4\0\26\22\2\0\21\22\1\u018f\4\22\21\0"+
    "\1\22\4\0\26\22\2\0\15\22\1\u0190\10\22\21\0"+
    "\1\22\4\0\26\22\2\0\22\22\1\u0191\3\22\21\0"+
    "\1\22\4\0\26\22\2\0\5\22\1\u0192\20\22\21\0"+
    "\1\22\4\0\26\22\2\0\6\22\1\u0193\17\22\21\0"+
    "\1\22\4\0\26\22\2\0\1\u0194\25\22\21\0\1\22"+
    "\4\0\26\22\2\0\16\22\1\u0195\7\22\21\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\u0196\20\22\21\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\u0197\4\22\21\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\u0198\4\22\21\0\1\22"+
    "\4\0\26\22\2\0\14\22\1\u0199\11\22\21\0\1\22"+
    "\4\0\26\22\2\0\10\22\1\u019a\15\22\21\0\1\22"+
    "\4\0\26\22\2\0\17\22\1\u019b\6\22\21\0\1\22"+
    "\4\0\26\22\2\0\17\22\1\u019c\6\22\21\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\u019d\20\22\21\0\1\22"+
    "\4\0\26\22\2\0\16\22\1\u019e\7\22\21\0\1\22"+
    "\4\0\26\22\2\0\5\22\1\u019f\20\22\21\0\1\22"+
    "\4\0\26\22\2\0\20\22\1\u01a0\5\22\21\0\1\22"+
    "\4\0\26\22\2\0\15\22\1\u01a1\10\22\21\0\1\22"+
    "\4\0\26\22\2\0\21\22\1\u01a2\4\22\21\0\1\22"+
    "\4\0\26\22\2\0\25\22\1\u01a3\21\0\1\22\4\0"+
    "\26\22\2\0\3\22\1\u01a4\22\22\21\0\1\22\4\0"+
    "\26\22\2\0\14\22\1\u01a5\11\22\21\0\1\22\4\0"+
    "\26\22\2\0\15\22\1\u01a6\10\22\21\0\1\22\4\0"+
    "\26\22\2\0\14\22\1\u01a7\11\22\21\0\1\22\4\0"+
    "\26\22\2\0\17\22\1\u01a8\6\22\21\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\u01a9\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\5\22\1\u01aa\20\22\21\0\1\22\4\0"+
    "\26\22\2\0\20\22\1\u01ab\5\22\21\0\1\22\4\0"+
    "\26\22\2\0\11\22\1\u01ac\14\22\21\0\1\22\4\0"+
    "\26\22\2\0\1\22\1\u01ad\24\22\21\0\1\22\4\0"+
    "\26\22\2\0\25\22\1\u01ae\21\0\1\22\4\0\26\22"+
    "\2\0\5\22\1\u01af\20\22\21\0\1\22\4\0\26\22"+
    "\2\0\14\22\1\u01b0\11\22\21\0\1\22\4\0\26\22"+
    "\2\0\12\22\1\u01b1\13\22\21\0\1\22\4\0\26\22"+
    "\2\0\21\22\1\u01b2\4\22\21\0\1\22\4\0\26\22"+
    "\2\0\21\22\1\u01b3\4\22\21\0\1\22\4\0\26\22"+
    "\2\0\20\22\1\u01b4\5\22\21\0\1\22\4\0\26\22"+
    "\2\0\25\22\1\u01b5\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[25228];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\3\1\3\11\2\1\1\11\13\1\2\11"+
    "\20\1\1\11\1\1\1\11\1\1\3\11\1\1\1\0"+
    "\3\11\42\1\2\11\u015b\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[437];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Lista para almacenar los errores léxicos y mostrarlos en el reporte
    public ArrayList<ErrorLexicoSintactico> erroresLexicos = new ArrayList<>();

    // Método auxiliar para generar tokens con su valor (lexema)
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    // Método auxiliar para generar tokens sin valor específico (como llaves o comas)
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case COMENTARIO_MULTILINEA: {
              erroresLexicos.add(new ErrorLexicoSintactico("Léxico", "Comentario multilínea '/*' no fue cerrado", yyline + 1, yycolumn + 1));
                              return symbol(sym.EOF);
            }  // fall though
            case 438: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { erroresLexicos.add(new ErrorLexicoSintactico("Léxico", "El carácter '" + yytext() + "' no pertenece al lenguaje", yyline + 1, yycolumn + 1));
            }
          // fall through
          case 79: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 80: break;
          case 3:
            { return symbol(sym.NOT, yytext());
            }
          // fall through
          case 81: break;
          case 4:
            { return symbol(sym.PARENTESIS_A, yytext());
            }
          // fall through
          case 82: break;
          case 5:
            { return symbol(sym.PARENTESIS_C, yytext());
            }
          // fall through
          case 83: break;
          case 6:
            { return symbol(sym.COMA, yytext());
            }
          // fall through
          case 84: break;
          case 7:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 85: break;
          case 8:
            { return symbol(sym.DOS_PUNTOS, yytext());
            }
          // fall through
          case 86: break;
          case 9:
            { return symbol(sym.MENOR, yytext());
            }
          // fall through
          case 87: break;
          case 10:
            { return symbol(sym.MAYOR, yytext());
            }
          // fall through
          case 88: break;
          case 11:
            { return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 89: break;
          case 12:
            { return symbol(sym.CORCHETE_A, yytext());
            }
          // fall through
          case 90: break;
          case 13:
            { return symbol(sym.CORCHETE_C, yytext());
            }
          // fall through
          case 91: break;
          case 14:
            { return symbol(sym.LLAVE_A, yytext());
            }
          // fall through
          case 92: break;
          case 15:
            { return symbol(sym.LLAVE_C, yytext());
            }
          // fall through
          case 93: break;
          case 16:
            { return symbol(sym.DIFERENTE, yytext());
            }
          // fall through
          case 94: break;
          case 17:
            { return symbol(sym.AND, yytext());
            }
          // fall through
          case 95: break;
          case 18:
            { yybegin(COMENTARIO_MULTILINEA);
            }
          // fall through
          case 96: break;
          case 19:
            { /* Ignorar, no se hace return */
            }
          // fall through
          case 97: break;
          case 20:
            { return symbol(sym.MENOR_IGUAL, yytext());
            }
          // fall through
          case 98: break;
          case 21:
            { return symbol(sym.IGUAL_IGUAL, yytext());
            }
          // fall through
          case 99: break;
          case 22:
            { return symbol(sym.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 100: break;
          case 23:
            { return symbol(sym.IF, yytext());
            }
          // fall through
          case 101: break;
          case 24:
            { return symbol(sym.OR, yytext());
            }
          // fall through
          case 102: break;
          case 25:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 103: break;
          case 26:
            { return symbol(sym.FLOTANTE, yytext());
            }
          // fall through
          case 104: break;
          case 27:
            { return symbol(sym.RUN, yytext());
            }
          // fall through
          case 105: break;
          case 28:
            { return symbol(sym.REST, yytext());
            }
          // fall through
          case 106: break;
          case 29:
            { return symbol(sym.ELSE, yytext());
            }
          // fall through
          case 107: break;
          case 30:
            { return symbol(sym.MAGE, yytext());
            }
          // fall through
          case 108: break;
          case 31:
            { return symbol(sym.MAIN, yytext());
            }
          // fall through
          case 109: break;
          case 32:
            { return symbol(sym.SEED, yytext());
            }
          // fall through
          case 110: break;
          case 33:
            { return symbol(sym.THEN, yytext());
            }
          // fall through
          case 111: break;
          case 34:
            { return symbol(sym.TRUE, yytext());
            }
          // fall through
          case 112: break;
          case 35:
            { return symbol(sym.WITH, yytext());
            }
          // fall through
          case 113: break;
          case 36:
            { return symbol(sym.SLASH, yytext());
            }
          // fall through
          case 114: break;
          case 37:
            { return symbol(sym.FALSE, yytext());
            }
          // fall through
          case 115: break;
          case 38:
            { return symbol(sym.MATCH, yytext());
            }
          // fall through
          case 116: break;
          case 39:
            { return symbol(sym.RULES, yytext());
            }
          // fall through
          case 117: break;
          case 40:
            { return symbol(sym.RANDOM, yytext());
            }
          // fall through
          case 118: break;
          case 41:
            { return symbol(sym.ROUNDS, yytext());
            }
          // fall through
          case 119: break;
          case 42:
            { return symbol(sym.WAR_CRY, yytext());
            }
          // fall through
          case 120: break;
          case 43:
            { return symbol(sym.BONUSES, yytext());
            }
          // fall through
          case 121: break;
          case 44:
            { return symbol(sym.INITIAL, yytext());
            }
          // fall through
          case 122: break;
          case 45:
            { return symbol(sym.PLAYERS, yytext());
            }
          // fall through
          case 123: break;
          case 46:
            { return symbol(sym.SCORING, yytext());
            }
          // fall through
          case 124: break;
          case 47:
            { return symbol(sym.WARRIOR, yytext());
            }
          // fall through
          case 125: break;
          case 48:
            { return symbol(sym.FIREBALL, yytext());
            }
          // fall through
          case 126: break;
          case 49:
            { return symbol(sym.MEDITATE, yytext());
            }
          // fall through
          case 127: break;
          case 50:
            { return symbol(sym.GET_MOVE, yytext());
            }
          // fall through
          case 128: break;
          case 51:
            { return symbol(sym.LAST_MOVE, yytext());
            }
          // fall through
          case 129: break;
          case 52:
            { return symbol(sym.MAGE_COMBO, yytext());
            }
          // fall through
          case 130: break;
          case 53:
            { return symbol(sym.SELF_SCORE, yytext());
            }
          // fall through
          case 131: break;
          case 54:
            { return symbol(sym.ARCANE_BOLT, yytext());
            }
          // fall through
          case 132: break;
          case 55:
            { return symbol(sym.SELF_HEALTH, yytext());
            }
          // fall through
          case 133: break;
          case 56:
            { return symbol(sym.HEALING_RUNE, yytext());
            }
          // fall through
          case 134: break;
          case 57:
            { return symbol(sym.HEAVY_STRIKE, yytext());
            }
          // fall through
          case 135: break;
          case 58:
            { return symbol(sym.SHIELD_BLOCK, yytext());
            }
          // fall through
          case 136: break;
          case 59:
            { return symbol(sym.DAMAGE_POINT, yytext());
            }
          // fall through
          case 137: break;
          case 60:
            { return symbol(sym.ROUND_NUMBER, yytext());
            }
          // fall through
          case 138: break;
          case 61:
            { return symbol(sym.SELF_HISTORY, yytext());
            }
          // fall through
          case 139: break;
          case 62:
            { return symbol(sym.TOTAL_ROUNDS, yytext());
            }
          // fall through
          case 140: break;
          case 63:
            { return symbol(sym.MAGIC_BARRIER, yytext());
            }
          // fall through
          case 141: break;
          case 64:
            { return symbol(sym.HEALING_POINT, yytext());
            }
          // fall through
          case 142: break;
          case 65:
            { return symbol(sym.SELF_RESOURCE, yytext());
            }
          // fall through
          case 143: break;
          case 66:
            { return symbol(sym.VICTORY_BONUS, yytext());
            }
          // fall through
          case 144: break;
          case 67:
            { return symbol(sym.WARRIOR_COMBO, yytext());
            }
          // fall through
          case 145: break;
          case 68:
            { return symbol(sym.OPPONENT_SCORE, yytext());
            }
          // fall through
          case 146: break;
          case 69:
            { return symbol(sym.GET_MOVES_COUNT, yytext());
            }
          // fall through
          case 147: break;
          case 70:
            { return symbol(sym.OPPONENT_HEALTH, yytext());
            }
          // fall through
          case 148: break;
          case 71:
            { return symbol(sym.GET_LAST_N_MOVES, yytext());
            }
          // fall through
          case 149: break;
          case 72:
            { return symbol(sym.OPPONENT_HISTORY, yytext());
            }
          // fall through
          case 150: break;
          case 73:
            { return symbol(sym.MAGE_COMBO_POINTS, yytext());
            }
          // fall through
          case 151: break;
          case 74:
            { return symbol(sym.OPPONENT_RESOURCE, yytext());
            }
          // fall through
          case 152: break;
          case 75:
            { return symbol(sym.LOW_HEALTH_VICTORY, yytext());
            }
          // fall through
          case 153: break;
          case 76:
            { return symbol(sym.SUCCESSFUL_DEFENSE, yytext());
            }
          // fall through
          case 154: break;
          case 77:
            { return symbol(sym.WARRIOR_COMBO_POINTS, yytext());
            }
          // fall through
          case 155: break;
          case 78:
            { return symbol(sym.FAILED_ACTION_PENALTY, yytext());
            }
          // fall through
          case 156: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
